sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Q66zSIG9F2HgIky8UogwcYakhA21joitSVXJUCfjnH4Z+6JHBsVf3FBmkZnWsunDfUsw3gDUb3Wp1MlAM6Uzval8dBlpIMqKSBMiyRHlQmjAEOEbXeCihtrpoODw/7Ia0+aQArd46ARh+TQyWKSzJEtz0AZSP/ngHnIqaVbfFAoeT3VXq1Jtvi90GCMVJ3IVtQq5MrGFbMiD+rIHB1VfjdY8dbDqdEGwHoXiAbp/pC0/6TlQk/iniyjMVVuLI0VgK1eX+9E67XjSA55be4X8pgCFZt9xpphxA1HOwEGhSLYy3RdMWJFAXHGhDiANPigcxTXM65nn5j+wdj3R8FHQ2yGjj2r5ouAFkgGau6vLVvVxIcr1isGYABA1IuTqwBVm6P+AV96zLR1Js1sOJ5AF6gDGZadmHyKYc3gjJBIOYaSZtooENAYMVCO9fLbrsGYVz7GYQPoMz6hjtr8IJl2PLKvI12g2CVWoIFU9mjjBSHSpoTSLxfm8HYXyxMigCbWBafzQk3qR9PQVTUyMte5603/Ej4S6lN0gPxUoJFFyfxSP7foI0yQL4ew9bm+3KjdA0nO/1zer3N0oqs7wdd+47kqX4L9cJOav3TgS99fYOm65TYaIAErUO5bHMZwovWmdg295dJGjvPm0+B4EXMmHxRqQvLbafaIjRHx/7tXchWI=
  - secure: bNcLnHvbqhXdxHTUG9bhapkWyakUp9PiHTgOdatEjGTJ1uTYmBsE1mPEKJNALDqfJB8ixMmCmtknFJAOZFKp0QRIKD2rhCwV4EAsvaJpe2q3NKy4wnqMQhDXGeNtyoIxePNU3OGurXZTAVIit5MaINNKqJrei5Lxj/D8axEq8tI7WSiMxTIB/LBrNpp7ffXhw7I/BtZLh5x7Z4TrxaUEf0OvlsfCeDT2FvmT7VSQZqW2arKAy7yBViXNePs0dURnI9ED6Etb4q2mtBS1bvYB2o2zsyo+8vWNwx+MbQUtECadTQMBLGpmPClA1WR4DWiwg8Wp7EDkCigkvGK5GJ9SuQmoFVjr3VPB5TKjfvX0+v7bzpPuS7TJpXfEqrluhvP/4M0ZcLV45y8wfYaRP2tmnp25nIr8YXvyMNPNQGoqoDyvsW9wR80fzu5r5t+mFGMkNKpTnhMuFyP3zq+TMhh8VT61ad+HL4eDRieVnNPABv8Un9oCscjTA2ifiEkeS9LemQGhkO55Bfbv/X2bbArKjAS/k6jZLVFMUGlEZbUxwUqvM4QN3ZoYbF8fnqTe2FkI3wcjyqyo0Be36Jr5RvS2NC2aJZuVCxsKVB8eW9UJLK0zfJ0YKI/pqyc6A5JrMy8z88wBNulRGwy98Hm1BrNFL7AxseJICECegmSg6QX0dvY=
  - secure: Km6pWsIQ7+78OtiVxmxKw3NZ5gH6Q1Sq+19ea7jv0cc2LH5p1/W6hGezieEKzTWac+vDPSsfYs47EzM2eW+LfwoDdZyJB1DgVMbQ6WAsldwWcbpbzE9lsELNBH4AfgZ4akOBchFZqOu87pM6qS2s5DgcydDS7ym6d+pbLdghG9dx4PjKc97fg5wP7XBmKVsvRmyq9mUCzFgKG8xIbXBra95seCDgBfxC2dp4NQx1ZaxYNFbCGwz1jt0SSUNjqpCz9eabeUfNwbAvSxINMxI47+8u/2tbYWVEKQx8aKYZGigSEh1r+kXVrWy7bKfAOcihtQeuM1uokbaDrScLXjr3n2pQbgjxBbECst85a9GdkXJGhUchwlsbB+YbC+8me2bs82Voc1XWw7zpC7GAQ6zsZJ2yXWxeg0Fh6fx1hoHX5zE/Qu8TOmOgQudSkv1HL2jsHbIEsSII/znf+ntdDKY9etSEa5b8Y+d0/THjS4t2Bvmo3lPKnfJO5gq4YXiiUmvlGJevUZitu6cBSlfVMk7aI84Pa6f++e+veXs9Wvym0vWWeyBJFf7OkrZm3QuQNBY4/eUr4TtSu1IcvVtUKfwoDtA3ZCtTQanvvwywlwKMYc0nk7QGF/F8gZDVIvAN228kpWlVTTwyb9sLkF1O/QS8ckuzM4ldHX8CRlJyvJg5DUg=
script: "./gradlew build"
after_success:
- "./gradlew coveralls"
deploy:
  provider: releases
  api_key:
    secure: mVH7dfsTbx9Oc0zpi+IjAdTZeqb6Y/B9c6k0L0+RHk74In6XMcxg+WEHzNeswODpRxOwryn53Fwrk615JFPQjXS2SgG4z08LYiExiRBCdzMu/FRqlen3WqO0Qlv/tzDVrSd+9EvCmWXa84M2e3U1trFDjr2MOwSvDfSWXfo/dqPXaVawwe8W5k+VapFxCW9xX3hfnzcIjJbAmGAOs6dpo5tABPJ7uXoi2VNP8nYMi6q4xd8Q8/KKlw4BFYDQwNO4a9WqyfvRc1h2haZx11u2+yg5aVyX81nsZv7KxzPvmFC0hzGB7jH2iwvPS9LnZg+O1Vug1TlC1DYDz1M2JIxNZfp1CMcHS6opllKR8THMcnfs/44AoKpLj5FpEYeglpQ5FyucQ9sLb2/lVNP/ZMSYKLoqZsTHSTee3s8kgJ0bIx9bEdUXfYozp3Jk4mzzN2JRZ0a9dQK/Hmchr4T4Rk7dKMHS8tinJUbt3vRaTLOpVqsKAQFOGlxs6zBYLu04eKKdtDTpKqRk6Fjwh2q12ztq0M8fglqKEwNxumA8PBXilgX5/pzJ+UeSNbcbFlI8eliVqKXpcaUN4RxBn4NJY9s2oJD4kKzgb8CZmkrICA/hlj+hwMVCX3kvaMW/n/mpTyBcgK0AiB5MwUXZZ51RI2tCi09WSH9i0zHd7QBIeUGMcTA=
  file:
  - build/distributions/ppt-museum-webapp-${TRAVIS_TAG}.zip
  - build/distributions/ppt-museum-webapp-${TRAVIS_TAG}.tar
  skip_cleanup: true
  all_branches: true
  on:
    repo: kaakaa/ppt-museum-webapp
    tags: true
after_deploy:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=kaakaa/ppt-museum-web
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO:$COMMIT
